In [23]:
import pandas as pd
import numpy as np

In [24]:
datos = pd.read_excel("C:\\Users\\eider\\Downloads\\información_préstamos.xlsx")

In [25]:
#Copia de seguridad del dataset original

df = datos.copy()

In [26]:
#Revisión inicial de estructura

df.shape

(255347, 19)

In [27]:
df.head()

,ID,Edad,Ingresos,Monto_Inicial,Scoring_Crediticio,Meses_Empleo,Num_Creditos,Ratio_Interes,Duracion,Ratio_Deuda_Ingresos,Estudios,Tipo_Jornada_Laboral,Estado_Civil,Posesion_Hipoteca,Personas_Cargo,Proposito,Fiador,Impago,Prima
0,S97R7X,18,61628,83011,397,113,1,8.06,48,0.45,Doctorado,Autónomo,Casado,1,0,Automóvil,0,0,155.80
1,T3ZE0N,69,19485,25474,784,46,2,15.04,48,0.15,Grado Universitario,Tiempo parcial,Soltero,0,1,Educación,0,0,24.20
2,RLGTBY,50,82410,68642,486,14,3,21.96,12,0.71,Escolar,Tiempo parcial,Divorciado,1,0,Automóvil,1,1,58.33
3,BZ86CV,64,132974,208339,308,10,1,24.26,12,0.61,Máster,Desempleado,Casado,1,0,Negocios,1,0,284.46
4,5OD75M,62,51411,113847,412,47,2,5.73,36,0.70,Grado Universitario,Autónomo,Casado,0,0,Negocios,0,0,101.77

In [28]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 255347 entries, 0 to 255346
Data columns (total 19 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   ID                    255347 non-null  object
 1   Edad                  255347 non-null  int64
 2   Ingresos              255347 non-null  int64
 3   Monto_Inicial         255347 non-null  int64
 4   Scoring_Crediticio    255347 non-null  int64
 5   Meses_Empleo          255347 non-null  int64
 6   Num_Creditos          255347 non-null  int64
 7   Ratio_Interes         255347 non-null  float64
 8   Duracion              255347 non-null  int64
 9   Ratio_Deuda_Ingresos  255347 non-null  float64
 10  Estudios              255347 non-null  object
 11  Tipo_Jornada_Laboral  255347 non-null  object
 12  Estado_Civil          255347 non-null  object
 13  Posesion_Hipoteca     255347 non-null  int64
 14  Personas_Cargo        255347 non-null  int64
 15  Proposito             255347 non-null  object
 16  Fiador                255347 non-null  int64
 17  Impago                255347 non-null  int64
 18  Prima                 255347 non-null  float64
dtypes: float64(3), int64(11), object(5)
memory usage: 37.0+ MB

In [29]:
#Comprobación de valores nulos

df.isnull().sum()

ID                      0
Edad                    0
Ingresos                0
Monto_Inicial           0
Scoring_Crediticio      0
Meses_Empleo            0
Num_Creditos            0
Ratio_Interes           0
Duracion                0
Ratio_Deuda_Ingresos    0
Estudios                0
Tipo_Jornada_Laboral    0
Estado_Civil            0
Posesion_Hipoteca       0
Personas_Cargo          0
Proposito               0
Fiador                  0
Impago                  0
Prima                   0
dtype: int64

No se detectan valores nulos en las variables clave, por lo que no ha sido necesario aplicar técnicas de imputación.

In [30]:
# Duplicados

df.duplicated().sum()

np.int64(0)

In [31]:
df.dtypes

ID                       object
Edad                      int64
Ingresos                  int64
Monto_Inicial             int64
Scoring_Crediticio        int64
Meses_Empleo              int64
Num_Creditos              int64
Ratio_Interes           float64
Duracion                  int64
Ratio_Deuda_Ingresos    float64
Estudios                 object
Tipo_Jornada_Laboral     object
Estado_Civil             object
Posesion_Hipoteca         int64
Personas_Cargo            int64
Proposito                object
Fiador                    int64
Impago                    int64
Prima                   float64
dtype: object

Se comprueba la consistencia de los tipos de datos para garantizar la correcta aplicación de los modelos financieros posteriores.

In [32]:
# Conversión de variables categóricas

variables_categoricas = [
    "Estudios",
    "Tipo_Jornada_Laboral",
    "Estado_Civil",
    "Proposito"
]

for col in variables_categoricas:
    df[col] = df[col].astype("category")

Las variables cualitativas se convierten al tipo category para reflejar correctamente su naturaleza no numérica y optimizar su tratamiento en los modelos posteriores.

In [33]:
# Conversión de variables binarias a tipo numérico compacto

variables_binarias = [
    "Posesion_Hipoteca",
    "Fiador",
    "Impago"
]

for col in variables_binarias:
    df[col] = df[col].astype("int8")

Las variables binarias se convierten a tipo numérico para garantizar su correcta interpretación en los modelos predictivos y en los cálculos financieros.

In [34]:
df.describe()

,Edad,Ingresos,Monto_Inicial,Scoring_Crediticio,Meses_Empleo,Num_Creditos,Ratio_Interes,Duracion,Ratio_Deuda_Ingresos,Posesion_Hipoteca,Personas_Cargo,Fiador,Impago,Prima
count,255347.000000,255347.000000,255347.000000,255347.000000,255347.000000,255347.000000,255347.000000,255347.000000,255347.000000,255347.000000,255347.000000,255347.000000,255347.000000,255347.000000
mean,43.498306,82499.304597,127578.865512,574.264346,59.541976,2.501036,13.492773,36.025894,0.500212,0.500014,0.500268,0.500108,0.116128,134.084211
std,14.990258,38963.013729,70840.706142,158.903867,34.643376,1.117018,6.636443,16.969330,0.230917,0.500001,0.500001,0.500001,0.320379,87.134582
min,18.000000,15000.000000,5000.000000,300.000000,0.000000,1.000000,2.000000,12.000000,0.100000,0.000000,0.000000,0.000000,0.000000,20.000000
25%,31.000000,48825.500000,66156.000000,437.000000,30.000000,2.000000,7.770000,24.000000,0.300000,0.000000,0.000000,0.000000,0.000000,63.200000
50%,43.000000,82466.000000,127556.000000,574.000000,60.000000,2.000000,13.460000,36.000000,0.500000,1.000000,1.000000,1.000000,0.000000,122.400000
75%,56.000000,116219.000000,188985.000000,712.000000,90.000000,3.000000,19.250000,48.000000,0.700000,1.000000,1.000000,1.000000,0.000000,188.430000
max,69.000000,149999.000000,249999.000000,849.000000,119.000000,4.000000,25.000000,60.000000,0.900000,1.000000,1.000000,1.000000,1.000000,771.500000

In [35]:
df["Interes_Anual"] = df["Ratio_Interes"] / 100

In [36]:
df.shape

(255347, 20)

In [37]:
# Tratamiento de outliers

variables_numericas = [
    "Edad", "Ingresos", "Monto_Inicial", "Scoring_Crediticio",
    "Meses_Empleo", "Num_Creditos", "Ratio_Interes",
    "Duracion", "Ratio_Deuda_Ingresos", "Prima"
]

for col in variables_numericas:
    q1 = df[col].quantile(0.01)
    q99 = df[col].quantile(0.99)
    df[col] = df[col].clip(lower=q1, upper=q99)

Este tratamiento resulta especialmente relevante en variables como ingresos, capital inicial o ratios financieros, donde valores atípicos pueden distorsionar estimaciones de cuotas, intereses y probabilidades de impago

In [38]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 255347 entries, 0 to 255346
Data columns (total 20 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   ID                    255347 non-null  object
 1   Edad                  255347 non-null  int64
 2   Ingresos              255347 non-null  float64
 3   Monto_Inicial         255347 non-null  float64
 4   Scoring_Crediticio    255347 non-null  int64
 5   Meses_Empleo          255347 non-null  int64
 6   Num_Creditos          255347 non-null  int64
 7   Ratio_Interes         255347 non-null  float64
 8   Duracion              255347 non-null  int64
 9   Ratio_Deuda_Ingresos  255347 non-null  float64
 10  Estudios              255347 non-null  category
 11  Tipo_Jornada_Laboral  255347 non-null  category
 12  Estado_Civil          255347 non-null  category
 13  Posesion_Hipoteca     255347 non-null  int8
 14  Personas_Cargo        255347 non-null  int64
 15  Proposito             255347 non-null  category
 16  Fiador                255347 non-null  int8
 17  Impago                255347 non-null  int8
 18  Prima                 255347 non-null  float64
 19  Interes_Anual         255347 non-null  float64
dtypes: category(4), float64(6), int64(6), int8(3), object(1)
memory usage: 27.0+ MB

In [39]:
df.describe(include="all")

,ID,Edad,Ingresos,Monto_Inicial,Scoring_Crediticio,Meses_Empleo,Num_Creditos,Ratio_Interes,Duracion,Ratio_Deuda_Ingresos,Estudios,Tipo_Jornada_Laboral,Estado_Civil,Posesion_Hipoteca,Personas_Cargo,Proposito,Fiador,Impago,Prima,Interes_Anual
count,255347,255347.000000,255347.000000,255347.000000,255347.000000,255347.000000,255347.000000,255347.000000,255347.000000,255347.000000,255347,255347,255347,255347.000000,255347.000000,255347,255347.000000,255347.000000,255347.000000,255347.000000
unique,255347,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4,4,3,NaN,NaN,5,NaN,NaN,NaN,NaN
top,G7MCLO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Grado Universitario,Tiempo parcial,Casado,NaN,NaN,Negocios,NaN,NaN,NaN,NaN
freq,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,64366,64161,85302,NaN,NaN,51298,NaN,NaN,NaN,NaN
mean,NaN,43.498306,82499.594269,127578.910542,574.264554,59.542098,2.501036,13.492802,36.025894,0.500212,NaN,NaN,NaN,0.500014,0.500268,NaN,0.500108,0.116128,133.553365,0.134928
std,NaN,14.990258,38939.988662,70798.937401,158.809939,34.615265,1.117018,6.632646,16.969330,0.230701,NaN,NaN,NaN,0.500001,0.500001,NaN,0.500001,0.320379,85.285225,0.066364
min,NaN,18.000000,16357.920000,7443.000000,305.000000,1.000000,1.000000,2.230000,12.000000,0.110000,NaN,NaN,NaN,0.000000,0.000000,NaN,0.000000,0.000000,20.000000,0.020000
25%,NaN,31.000000,48825.500000,66156.000000,437.000000,30.000000,2.000000,7.770000,24.000000,0.300000,NaN,NaN,NaN,0.000000,0.000000,NaN,0.000000,0.000000,63.200000,0.077700
50%,NaN,43.000000,82466.000000,127556.000000,574.000000,60.000000,2.000000,13.460000,36.000000,0.500000,NaN,NaN,NaN,1.000000,1.000000,NaN,1.000000,0.000000,122.400000,0.134600
75%,NaN,56.000000,116219.000000,188985.000000,712.000000,90.000000,3.000000,19.250000,48.000000,0.700000,NaN,NaN,NaN,1.000000,1.000000,NaN,1.000000,0.000000,188.430000,0.192500
max,NaN,69.000000,148661.000000,247545.540000,844.000000,118.000000,4.000000,24.780000,60.000000,0.890000,NaN,NaN,NaN,1.000000,1.000000,NaN,1.000000,1.000000,381.605400,0.250000

In [40]:
df.head()

,ID,Edad,Ingresos,Monto_Inicial,Scoring_Crediticio,Meses_Empleo,Num_Creditos,Ratio_Interes,Duracion,Ratio_Deuda_Ingresos,Estudios,Tipo_Jornada_Laboral,Estado_Civil,Posesion_Hipoteca,Personas_Cargo,Proposito,Fiador,Impago,Prima,Interes_Anual
0,S97R7X,18,61628.0,83011.0,397,113,1,8.06,48,0.45,Doctorado,Autónomo,Casado,1,0,Automóvil,0,0,155.80,0.0806
1,T3ZE0N,69,19485.0,25474.0,784,46,2,15.04,48,0.15,Grado Universitario,Tiempo parcial,Soltero,0,1,Educación,0,0,24.20,0.1504
2,RLGTBY,50,82410.0,68642.0,486,14,3,21.96,12,0.71,Escolar,Tiempo parcial,Divorciado,1,0,Automóvil,1,1,58.33,0.2196
3,BZ86CV,64,132974.0,208339.0,308,10,1,24.26,12,0.61,Máster,Desempleado,Casado,1,0,Negocios,1,0,284.46,0.2426
4,5OD75M,62,51411.0,113847.0,412,47,2,5.73,36,0.70,Grado Universitario,Autónomo,Casado,0,0,Negocios,0,0,101.77,0.0573

In [41]:
df.to_csv("datos_prestamos_limpios.csv", index=False, encoding="utf-8")