In [1]:
import pandas as pd
import numpy as np

In [ ]:

datos = pd.read_excel("../Datos/Originales/Prestamos_Data_Alumnos_v2.xlsx")

In [5]:
#Copia de seguridad del dataset original

df = datos.copy()

In [6]:
#Revisión inicial de estructura

df.shape

(255347, 19)

In [7]:
df.head()

,ID,Edad,Ingresos,Monto_Inicial,Scoring_Crediticio,Meses_Empleo,Num_Creditos,Ratio_Interes,Duracion,Ratio_Deuda_Ingresos,Estudios,Tipo_Jornada_Laboral,Estado_Civil,Posesion_Hipoteca,Personas_Cargo,Proposito,Fiador,Impago,Prima
0,S97R7X,18,16000,5000,397,19,1,8.06,48,0.10,Escolar,Autónomo,Soltero,1,0,Automóvil,0,0,15.0
1,T3ZE0N,69,72673,32340,784,320,2,15.04,48,0.12,Doctorado,Tiempo parcial,Casado,0,1,Educación,0,0,15.0
2,RLGTBY,50,62116,37278,486,217,3,21.96,12,0.55,Grado Universitario,Tiempo parcial,Casado,1,0,Automóvil,1,1,15.0
3,BZ86CV,64,59846,19784,308,340,1,24.26,12,0.35,Grado Universitario,Desempleado,Divorciado,1,0,Negocios,1,0,15.0
4,5OD75M,62,28413,13751,412,476,2,5.73,36,0.14,Escolar,Autónomo,Casado,0,0,Negocios,0,0,15.0

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 255347 entries, 0 to 255346
Data columns (total 19 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   ID                    255347 non-null  object
 1   Edad                  255347 non-null  int64
 2   Ingresos              255347 non-null  int64
 3   Monto_Inicial         255347 non-null  int64
 4   Scoring_Crediticio    255347 non-null  int64
 5   Meses_Empleo          255347 non-null  int64
 6   Num_Creditos          255347 non-null  int64
 7   Ratio_Interes         255347 non-null  float64
 8   Duracion              255347 non-null  int64
 9   Ratio_Deuda_Ingresos  255347 non-null  float64
 10  Estudios              255347 non-null  object
 11  Tipo_Jornada_Laboral  255347 non-null  object
 12  Estado_Civil          255347 non-null  object
 13  Posesion_Hipoteca     255347 non-null  int64
 14  Personas_Cargo        255347 non-null  int64
 15  Proposito             255347 non-null  object
 16  Fiador                255347 non-null  int64
 17  Impago                255347 non-null  int64
 18  Prima                 255347 non-null  float64
dtypes: float64(3), int64(11), object(5)
memory usage: 37.0+ MB

In [9]:
#Comprobación de valores nulos

df.isnull().sum()

ID                      0
Edad                    0
Ingresos                0
Monto_Inicial           0
Scoring_Crediticio      0
Meses_Empleo            0
Num_Creditos            0
Ratio_Interes           0
Duracion                0
Ratio_Deuda_Ingresos    0
Estudios                0
Tipo_Jornada_Laboral    0
Estado_Civil            0
Posesion_Hipoteca       0
Personas_Cargo          0
Proposito               0
Fiador                  0
Impago                  0
Prima                   0
dtype: int64

No se detectan valores nulos en las variables clave, por lo que no ha sido necesario aplicar técnicas de imputación.

In [10]:
# Duplicados

df.duplicated().sum()

np.int64(0)

In [11]:
df.dtypes

ID                       object
Edad                      int64
Ingresos                  int64
Monto_Inicial             int64
Scoring_Crediticio        int64
Meses_Empleo              int64
Num_Creditos              int64
Ratio_Interes           float64
Duracion                  int64
Ratio_Deuda_Ingresos    float64
Estudios                 object
Tipo_Jornada_Laboral     object
Estado_Civil             object
Posesion_Hipoteca         int64
Personas_Cargo            int64
Proposito                object
Fiador                    int64
Impago                    int64
Prima                   float64
dtype: object

Se comprueba la consistencia de los tipos de datos para garantizar la correcta aplicación de los modelos financieros posteriores.

In [12]:
# Conversión de variables categóricas

variables_categoricas = [
    "Estudios",
    "Tipo_Jornada_Laboral",
    "Estado_Civil",
    "Proposito"
]

for col in variables_categoricas:
    df[col] = df[col].astype("category")

Las variables cualitativas se convierten al tipo category para reflejar correctamente su naturaleza no numérica y optimizar su tratamiento en los modelos posteriores.

In [13]:
# Conversión de variables binarias a tipo numérico compacto

variables_binarias = [
    "Posesion_Hipoteca",
    "Fiador",
    "Impago"
]

for col in variables_binarias:
    df[col] = df[col].astype("int8")

Las variables binarias se convierten a tipo numérico para garantizar su correcta interpretación en los modelos predictivos y en los cálculos financieros.

In [14]:
df.describe()

,Edad,Ingresos,Monto_Inicial,Scoring_Crediticio,Meses_Empleo,Num_Creditos,Ratio_Interes,Duracion,Ratio_Deuda_Ingresos,Posesion_Hipoteca,Personas_Cargo,Fiador,Impago,Prima
count,255347.000000,255347.000000,255347.000000,255347.000000,255347.000000,255347.000000,255347.000000,255347.000000,255347.000000,255347.000000,255347.000000,255347.000000,255347.000000,255347.000000
mean,43.498306,41504.419931,45045.395235,574.264346,212.686587,2.501036,13.492773,36.025894,0.321257,0.500014,0.500268,0.500108,0.116128,18.009695
std,14.990258,16016.702191,46632.175369,158.903867,150.823628,1.117018,6.636443,16.969330,0.181097,0.500001,0.500001,0.500001,0.320379,9.292141
min,18.000000,16000.000000,3000.000000,300.000000,0.000000,1.000000,2.000000,12.000000,0.100000,0.000000,0.000000,0.000000,0.000000,15.000000
25%,31.000000,30481.000000,15033.000000,437.000000,69.000000,2.000000,7.770000,24.000000,0.140000,0.000000,0.000000,0.000000,0.000000,15.000000
50%,43.000000,39099.000000,40000.000000,574.000000,207.000000,2.000000,13.460000,36.000000,0.290000,1.000000,1.000000,1.000000,0.000000,15.000000
75%,56.000000,50083.000000,47325.000000,712.000000,337.000000,3.000000,19.250000,48.000000,0.550000,1.000000,1.000000,1.000000,0.000000,15.000000
max,69.000000,120000.000000,400000.000000,849.000000,639.000000,4.000000,25.000000,60.000000,0.550000,1.000000,1.000000,1.000000,1.000000,139.660000

In [15]:
df["Interes_Anual"] = df["Ratio_Interes"] / 100

In [16]:
df.shape

(255347, 20)

In [17]:
# Tratamiento de outliers

variables_numericas = [
    "Edad", "Ingresos", "Monto_Inicial", "Scoring_Crediticio",
    "Meses_Empleo", "Num_Creditos", "Ratio_Interes",
    "Duracion", "Ratio_Deuda_Ingresos", "Prima"
]

for col in variables_numericas:
    q1 = df[col].quantile(0.01)
    q99 = df[col].quantile(0.99)
    df[col] = df[col].clip(lower=q1, upper=q99)

Este tratamiento resulta especialmente relevante en variables como ingresos, capital inicial o ratios financieros, donde valores atípicos pueden distorsionar estimaciones de cuotas, intereses y probabilidades de impago

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 255347 entries, 0 to 255346
Data columns (total 20 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   ID                    255347 non-null  object
 1   Edad                  255347 non-null  int64
 2   Ingresos              255347 non-null  float64
 3   Monto_Inicial         255347 non-null  float64
 4   Scoring_Crediticio    255347 non-null  int64
 5   Meses_Empleo          255347 non-null  int64
 6   Num_Creditos          255347 non-null  int64
 7   Ratio_Interes         255347 non-null  float64
 8   Duracion              255347 non-null  int64
 9   Ratio_Deuda_Ingresos  255347 non-null  float64
 10  Estudios              255347 non-null  category
 11  Tipo_Jornada_Laboral  255347 non-null  category
 12  Estado_Civil          255347 non-null  category
 13  Posesion_Hipoteca     255347 non-null  int8
 14  Personas_Cargo        255347 non-null  int64
 15  Proposito             255347 non-null  category
 16  Fiador                255347 non-null  int8
 17  Impago                255347 non-null  int8
 18  Prima                 255347 non-null  float64
 19  Interes_Anual         255347 non-null  float64
dtypes: category(4), float64(6), int64(6), int8(3), object(1)
memory usage: 27.0+ MB

In [19]:
df.describe(include="all")

,ID,Edad,Ingresos,Monto_Inicial,Scoring_Crediticio,Meses_Empleo,Num_Creditos,Ratio_Interes,Duracion,Ratio_Deuda_Ingresos,Estudios,Tipo_Jornada_Laboral,Estado_Civil,Posesion_Hipoteca,Personas_Cargo,Proposito,Fiador,Impago,Prima,Interes_Anual
count,255347,255347.000000,255347.000000,255347.000000,255347.000000,255347.000000,255347.000000,255347.000000,255347.000000,255347.000000,255347,255347,255347,255347.000000,255347.000000,255347,255347.000000,255347.000000,255347.000000,255347.000000
unique,255347,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4,4,3,NaN,NaN,5,NaN,NaN,NaN,NaN
top,S97R7X,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Escolar,Tiempo parcial,Casado,NaN,NaN,Negocios,NaN,NaN,NaN,NaN
freq,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,99537,64161,126629,NaN,NaN,51298,NaN,NaN,NaN,NaN
mean,NaN,43.498306,41417.343716,44500.587278,574.264554,212.431671,2.501036,13.492802,36.025894,0.321257,NaN,NaN,NaN,0.500014,0.500268,NaN,0.500108,0.116128,17.843608,0.134928
std,NaN,14.990258,15708.568286,43769.394991,158.809939,150.256753,1.117018,6.632646,16.969330,0.181097,NaN,NaN,NaN,0.500001,0.500001,NaN,0.500001,0.320379,8.161574,0.066364
min,NaN,18.000000,16000.000000,3000.000000,305.000000,0.000000,1.000000,2.230000,12.000000,0.100000,NaN,NaN,NaN,0.000000,0.000000,NaN,0.000000,0.000000,15.000000,0.020000
25%,NaN,31.000000,30481.000000,15033.000000,437.000000,69.000000,2.000000,7.770000,24.000000,0.140000,NaN,NaN,NaN,0.000000,0.000000,NaN,0.000000,0.000000,15.000000,0.077700
50%,NaN,43.000000,39099.000000,40000.000000,574.000000,207.000000,2.000000,13.460000,36.000000,0.290000,NaN,NaN,NaN,1.000000,1.000000,NaN,1.000000,0.000000,15.000000,0.134600
75%,NaN,56.000000,50083.000000,47325.000000,712.000000,337.000000,3.000000,19.250000,48.000000,0.550000,NaN,NaN,NaN,1.000000,1.000000,NaN,1.000000,0.000000,15.000000,0.192500
max,NaN,69.000000,90079.480000,234918.900000,844.000000,526.000000,4.000000,24.780000,60.000000,0.550000,NaN,NaN,NaN,1.000000,1.000000,NaN,1.000000,1.000000,61.875400,0.250000

In [20]:
df.head()

,ID,Edad,Ingresos,Monto_Inicial,Scoring_Crediticio,Meses_Empleo,Num_Creditos,Ratio_Interes,Duracion,Ratio_Deuda_Ingresos,Estudios,Tipo_Jornada_Laboral,Estado_Civil,Posesion_Hipoteca,Personas_Cargo,Proposito,Fiador,Impago,Prima,Interes_Anual
0,S97R7X,18,16000.0,5000.0,397,19,1,8.06,48,0.10,Escolar,Autónomo,Soltero,1,0,Automóvil,0,0,15.0,0.0806
1,T3ZE0N,69,72673.0,32340.0,784,320,2,15.04,48,0.12,Doctorado,Tiempo parcial,Casado,0,1,Educación,0,0,15.0,0.1504
2,RLGTBY,50,62116.0,37278.0,486,217,3,21.96,12,0.55,Grado Universitario,Tiempo parcial,Casado,1,0,Automóvil,1,1,15.0,0.2196
3,BZ86CV,64,59846.0,19784.0,308,340,1,24.26,12,0.35,Grado Universitario,Desempleado,Divorciado,1,0,Negocios,1,0,15.0,0.2426
4,5OD75M,62,28413.0,13751.0,412,476,2,5.73,36,0.14,Escolar,Autónomo,Casado,0,0,Negocios,0,0,15.0,0.0573

In [21]:
df.to_csv("datos_prestamos_limpios.csv", index=False, encoding="utf-8")